apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Peribolos
  description: Declarative GitHub Organization management via Peribolos as a service
  links:
    - url: https://github.com/operate-first/peribolos-as-a-service/blob/main/SUPPORT.md
      title: Support path
      icon: user
  annotations:
    operate-first.cloud/component-icon-url: https://raw.githubusercontent.com/operate-first/peribolos-as-a-service/main/static/robot.svg
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: group:operate-first
  system: system:operate-first-cloud
