---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run
spec:
  params:
    - name: REPO_NAME
      type: string
      default: ".github"
    - name: SECRET_NAME
      type: string
    - name: CHECK_RUN_ID
      type: string
  steps:
    - name: apply-peribolos
      image: toolbox
      volumeMounts:
        - mountPath: /mnt/secret
          name: github-token
      env:
        - name: ORG_NAME
          valueFrom:
            secretKeyRef:
              name: $(params.SECRET_NAME)
              key: orgName
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.SECRET_NAME)
              key: token
      script: |
        #!/usr/bin/bash

        echo "Updating check run to in-progress..."
        curl -X PATCH \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          https://api.github.com/repos/$ORG_NAME/.github/check-runs/$(params.CHECK_RUN_ID) \
          -d '{"status":"in_progress"}'

        echo "Cloning repository..."
        # Clone repository
        git clone https://github.com/$ORG_NAME/$(params.REPO_NAME)
        cd $(params.REPO_NAME)

        # Run Peribolos on the repository
        echo "Running peribolos on commit $(git rev-parse --short HEAD)..."
        peribolos --config-path peribolos.yaml --github-token-path /mnt/secret/token --fix-org --fix-repos --fix-team-members --fix-teams --fix-team-repos --confirm

        if [ $? -eq 0 ]; then
          CONCLUSION="success"
        else
          CONCLUSION="failure"
        fi

        echo "Updating check run to completed with $CONCLUSION..."
        curl -X PATCH \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          https://api.github.com/repos/$ORG_NAME/.github/check-runs/$(params.CHECK_RUN_ID) \
          -d "{\"status\":\"completed\",\"conclusion\":\"$CONCLUSION\"}"

  volumes:
    - name: github-token
      secret:
        secretName: $(params.SECRET_NAME)
        items:
          - key: token
            path: token
        optional: false
